/* Gnosis system map — full content model (data-driven; v3 can later feed this from otter-docs).
   Every node and every edge carries a dossier-grade spec. Facts verified against the live repo
   2026-05-28. The engine (tour.html) auto-lays-out nodes inside regions and auto-builds the tour. */
window.SYS = {
  world: { w: 5200, h: 2900 },

  // regions: x,y top-left; cols = how many columns to stack nodes in. Engine sizes the box.
  regions: [
    { id:"ing",  label:"Ingestion",  cls:"ing",  x:470,  y:1240, cols:1 },
    { id:"pipe", label:"Pipeline agents", cls:"pipe", x:1320, y:120, cols:4 },
    { id:"wf",   label:"AI Workforce · Bamboo", cls:"wf", x:1320, y:1500, cols:3 },
    { id:"data", label:"Data",       cls:"data", x:2980, y:120,  cols:3 },
    { id:"inf",  label:"Inference · local-first", cls:"inf", x:2980, y:1240, cols:2 },
    { id:"surf", label:"Surfaces",   cls:"surf", x:3880, y:1240, cols:1 },
    { id:"prod", label:"Products",   cls:"prod", x:4420, y:980,  cols:2 },
  ],

  // the bus is a standalone hub between ingestion and the agent regions
  bus: { id:"bus", x:880, y:1230, w:380, h:170,
    label:"EVENT BUS", detail:"Redpanda · 60 events · 16 partitions",
    spec:"Redpanda (Kafka API). Every action is an event and no agent calls another directly — 60 typed event classes, 16 partitions with entity-aware keys — so the whole system is logged, replayable, and auditable by construction." },

  nodes: [
    // ── External dependencies (each placed beside the region it relates to; dashed = external) ──
    { id:"braedon", r:"surf", ext:true, label:"Braedon", detail:"operator", spec:"Sole operator / architect — sets direction; the platform runs the loop." },
    { id:"users",   r:"prod", ext:true, label:"Users / prospects", detail:"use the products", spec:"Prospective users of the public product surfaces." },
    { id:"sources", r:"ing",  ext:true, label:"Public data sources", detail:"FEC · EDGAR · USASpending · Congress · registries · civic", spec:"The public record: FEC, EDGAR, USASpending, Congress, ~25 aviation registries, civic platforms." },
    { id:"claude",  r:"inf",  ext:true, label:"Anthropic Claude", detail:"Opus 4.7 · flat-rate sub", spec:"Frontier inference on a flat-rate subscription — the hard ~5%: coding and top-level orchestration. External / cloud, not local." },
    { id:"cloudflare", r:"prod", ext:true, label:"Cloudflare edge", detail:"Workers · D1 · R2 · KV · Tunnel", spec:"The edge platform the product surfaces run on; a Tunnel exposes the operator dashboard." },

    // ── Ingestion ──
    { id:"ingest", r:"ing", label:"Ingest adapters", detail:"147 source configs", spec:"147 source configs pull the public record on cron — per-source quotas, circuit breakers, cursor backfill — and publish one typed IngestRecord per pull to the bus." },

    // ── Pipeline agents (consume the bus) ──
    { id:"knowledge", r:"pipe", label:"knowledge ×4", detail:"entity resolution", spec:"Four replicas resolve entities (5-tier) and MERGE them into the knowledge graph; entity-aware partitioning prevents MERGE races." },
    { id:"whwriter",  r:"pipe", label:"warehouse writer", detail:"fast PG writer", spec:"Lands time-series + relational rows into the Postgres warehouse." },
    { id:"analyst",   r:"pipe", label:"analyst", detail:"TabPFN anomalies", spec:"Anomaly detection (TabPFN) + statistical regime / shape / correlation detection over the warehouse." },
    { id:"enrichment",r:"pipe", label:"enrichment", detail:"KG claims + edges", spec:"The enrichment cycle synthesizes findings into knowledge-graph Claims and SUPPORTS edges." },
    { id:"research",  r:"pipe", label:"research", detail:"6-stage + cache", spec:"Six-stage autonomous research pipeline with a semantic cache." },
    { id:"quant",     r:"pipe", label:"quant", detail:"7-stage", spec:"Seven-stage quantitative workflow over the warehouse and search." },
    { id:"geo",       r:"pipe", label:"geopolitical", detail:"ACH · PMESII-PT · DIME", spec:"Structured geopolitical analysis frameworks (ACH, PMESII-PT, DIME)." },
    { id:"social",    r:"pipe", label:"social", detail:"concierge", spec:"Concierge / social workflow." },
    { id:"flow",      r:"pipe", label:"flow", detail:"power-flow daemon", spec:"Continuous power-flow intelligence daemon." },
    { id:"qa",        r:"pipe", label:"qa", detail:"health + freshness", spec:"Eight service health checks plus warehouse-freshness and test-suite runs, nightly." },
    { id:"comber",    r:"pipe", label:"comber", detail:"observe-only checks", spec:"Eleven deterministic data-quality checks, observe-only." },
    { id:"emaila",    r:"pipe", label:"email-analyzer", detail:"email anatomy", spec:"Email-anatomy analysis." },
    { id:"compilation",r:"pipe",label:"compilation", detail:"knowledge compilation", spec:"Knowledge-compilation — synthesizes enrichment findings into KG claims/edges (Phase 10)." },
    { id:"scoutc",    r:"pipe", label:"scout-consumer", detail:"Scout SaaS events", spec:"Ingests Scout SaaS events back into the platform." },

    // ── AI Workforce (Bamboo harness) ──
    { id:"cosmo", r:"wf", label:"Cosmo", detail:"chief of staff · Claude", spec:"Persistent chief-of-staff on Claude Opus 4.7. Manages your attention, delegates work as cards, owns the board, holds core + procedural memory across restarts (~38 tools). The judgment seat." },
    { id:"orca",  r:"wf", label:"Orca", detail:"orchestrator/triage · 27B", spec:"Always-on local-27B triage between the bus and Cosmo (escalate/answer/buffer/drop). Scores proposals deterministically and dispatches cards. Fail-safe: rate-capped, deduped, escalations never dropped." },
    { id:"eagle", r:"wf", label:"Eagle", detail:"sales engine", spec:"Sales-intelligence engine — frontier (Agent SDK) for the owner org, local 27B for client orgs. Returns structured JSON; code does the writes." },
    { id:"dispatcher", r:"wf", label:"dispatcher", detail:"spawns workers", spec:"Spawns one ephemeral worker container per card (docker run --rm) with hard timeouts, memory limits and scoped permissions." },
    { id:"coder", r:"wf", label:"Coder", detail:"worker · Claude", spec:"Ephemeral worker (Claude): review, implement, test, commit — spawned per card, then gone." },
    { id:"researcher", r:"wf", label:"Researcher", detail:"worker · 27B", spec:"Ephemeral worker (27B): dispatched research per card." },
    { id:"executor", r:"wf", label:"Executor", detail:"worker · 27B", spec:"Ephemeral worker (27B): Docker-gated execution — test, rebuild, deploy." },
    { id:"consolidator", r:"wf", label:"Consolidator", detail:"worker · 27B", spec:"Ephemeral worker (27B): summarizes conversation context into core memory." },
    { id:"labbot", r:"wf", label:"Lab Bot", detail:"worker · Claude", spec:"Experimental research worker (Claude)." },
    { id:"seedr", r:"wf", label:"Seed Researcher", detail:"worker · Claude", spec:"Entity-scoped research worker (Claude)." },
    { id:"kanban", r:"data", label:"Kanban board", detail:"Postgres-backed · 11-lane walk", spec:"A Postgres-backed work board (the gnosis_kanban DB) — an 11-lane card walk with heartbeats and durability sweeps. It's a store, not a Bamboo agent: Cosmo owns it and Orca dispatches from it, but the board itself lives in the data layer." },
    { id:"sentinel", r:"wf", label:"Sentinel", detail:"SRE · TS/Node", spec:"SRE sidecar (TypeScript). Measures liveness by real work progress — consumer lag, model health, container liveness — not heartbeats, and self-heals two specific failure modes." },

    // ── Inference ──
    { id:"router", r:"inf", label:"LLM Router", detail:"tasks→9B · agents→27B/Claude · embeds→nomic", spec:"Go router. Sends 11 task types to the 9B, agent conversations to the 27B or Claude (per agents.yaml), embeddings to nomic. OpenAI-compatible; every call has a non-LLM heuristic fallback." },
    { id:"m9b",  r:"inf", label:"Qwen 9B Q5_K_M", detail:"4070 · task NLP", spec:"On the RTX 4070 — extraction, classification, summarization, and the other 11 task types." },
    { id:"m27b", r:"inf", label:"Qwen 27B Q6_K", detail:"5090 · turbo3 → 524K ctx", spec:"The agent workhorse on the RTX 5090. turbo3 KV compression (TurboQuant, configured + validated) fits 524K context across 3 slots at ~55 tok/s on one 32 GB card." },
    { id:"nomic", r:"inf", label:"nomic-embed", detail:"embeddings", spec:"nomic-embed-text — vector embeddings." },

    // ── Data ──
    { id:"neo4j", r:"data", label:"Knowledge graph", detail:"Neo4j 5.26", spec:"Entities, relationships, provenance, power flows (Neo4j 5.26, native on m000003)." },
    { id:"postgres", r:"data", label:"Warehouse", detail:"Postgres 16 + pgvector", spec:"Time-series, relational, and vector embeddings (Postgres 16 + pgvector, native on m000003)." },
    { id:"elastic", r:"data", label:"Search", detail:"Elasticsearch 8.12", spec:"Full-text / field search for research and enrichment." },
    { id:"redis", r:"data", label:"Cache / queue", detail:"Redis 7", spec:"Inference cache, GPU queue, agent working memory, learned thresholds." },
    { id:"keycloak", r:"data", label:"Identity", detail:"Keycloak 26", spec:"OAuth2 / OIDC for the operator and the product surfaces." },

    // ── Surfaces ──
    { id:"gateway", r:"surf", label:"API Gateway", detail:"Go · REST + WS · 84 routes", spec:"Go (chi) gateway — REST + WebSocket, 84 routes: auth, feed, chat, KG/warehouse queries, kanban, push." },
    { id:"pwa", r:"surf", label:"Operator dashboard", detail:"PWA · private", spec:"React PWA at gnosis.blong.dev — feed, Cosmo chat, board, audit, map, sentinel. Private, Keycloak-gated; never public." },

    // ── Products ──
    { id:"tailatlas", r:"prod", label:"Tail Atlas", detail:"GA fleet intelligence", spec:"Global GA fleet intelligence — 710K aircraft + 313K owners reconciled from ~25 registries. React + Hono on Cloudflare, D1 + R2." },
    { id:"telekora", r:"prod", label:"Telekora", detail:"B2B LMS", spec:"Multi-tenant B2B LMS — bring-your-own-LLM course generation (per-tenant keys envelope-encrypted), Stripe, Telegram. telekora.com." },
    { id:"hometownwire", r:"prod", label:"HometownWire", detail:"civic intelligence", spec:"Civic intelligence — public-meeting corpus made searchable; lands through the same gnosis pipeline as everything else." },
    { id:"scout", r:"prod", label:"Scout", detail:"B2B sales intel", spec:"B2B sales-intelligence SaaS surface (Hono + React + D1 on Workers) — the public face of the Eagle engine." },
    { id:"portf", r:"prod", label:"Port Foliopolis", detail:"this site", spec:"This site — a Phaser game with LLM-driven NPCs on free-tier models behind a fail-closed cost guard." },
    { id:"dreamtree", r:"prod", label:"DreamTree", detail:"data sovereignty", spec:"A data-sovereignty project. Kept intentionally vague for now." },
  ],

  edges: [
    { a:"braedon", b:"pwa", spec:"Braedon operates the platform through the dashboard." },
    { a:"pwa", b:"gateway", spec:"The PWA calls the gateway (HTTPS / WebSocket)." },
    { a:"users", b:"scout", dotted:true, spec:"Users reach the product surfaces." },
    { a:"users", b:"tailatlas", dotted:true, spec:"Users reach the product surfaces." },
    { a:"users", b:"telekora", dotted:true, spec:"Users reach the product surfaces." },
    { a:"scout", b:"gateway", spec:"Products read the corpus / write intent through the gateway (service key)." },
    { a:"tailatlas", b:"gateway", spec:"Products read the corpus / write intent through the gateway (service key)." },
    { a:"telekora", b:"gateway", spec:"Products read the corpus / write intent through the gateway (service key)." },
    { a:"hometownwire", b:"gateway", spec:"Civic data lands and is read through the gateway / shared pipeline." },
    { a:"sources", b:"ingest", spec:"Ingest adapters pull from the public sources." },
    { a:"ingest", b:"bus", spec:"One typed IngestRecord per pull → ingest.source.<id> + the 16-partition ingest.records (Kafka)." },
    { a:"bus", b:"knowledge", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"whwriter", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"analyst", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"enrichment", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"research", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"quant", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"geo", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"social", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"flow", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"qa", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"comber", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"emaila", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"compilation", spec:"Pipeline agents consume events off the bus." },
    { a:"bus", b:"scoutc", spec:"Pipeline agents consume events off the bus." },
    { a:"knowledge", b:"neo4j", spec:"Knowledge agents MERGE entities + relationships into the graph." },
    { a:"enrichment", b:"neo4j", spec:"Enrichment writes Claims + SUPPORTS edges to the graph." },
    { a:"compilation", b:"neo4j", spec:"Compiled findings land as graph claims/edges." },
    { a:"whwriter", b:"postgres", spec:"The warehouse writer lands rows in Postgres." },
    { a:"analyst", b:"postgres", spec:"Analyst reads/writes the warehouse." },
    { a:"research", b:"elastic", spec:"Research queries full-text search." },
    { a:"quant", b:"elastic", spec:"Quant queries search + warehouse." },
    { a:"bus", b:"orca", spec:"Orca consumes every bus signal and triages it." },
    { a:"orca", b:"bus", spec:"Orca publishes triage outcomes / dispatch back to the bus." },
    { a:"orca", b:"kanban", spec:"Orca scores ready proposals deterministically and advances / dispatches cards onto the 11-lane board." },
    { a:"orca", b:"router", spec:"Orca triages on the local 27B." },
    { a:"bus", b:"cosmo", spec:"Cosmo reacts to escalations + dispatch results off the bus." },
    { a:"cosmo", b:"kanban", spec:"Cosmo owns the board — creates cards, walks lanes, delegates." },
    { a:"cosmo", b:"gateway", spec:"Cosmo delivers cards / chat to the operator via the gateway." },
    { a:"cosmo", b:"router", spec:"Cosmo's turns run on Claude via the router." },
    { a:"cosmo", b:"redis", spec:"Cosmo's working-memory scratchpad." },
    { a:"bus", b:"eagle", spec:"Eagle reacts to outreach events on the bus." },
    { a:"eagle", b:"router", spec:"Eagle drafts via the 27B or Claude SDK." },
    { a:"bus", b:"dispatcher", spec:"cmd.dispatch.<name> rides the bus; the dispatcher spawns the matching worker." },
    { a:"dispatcher", b:"coder", spec:"One ephemeral worker per card." },
    { a:"dispatcher", b:"researcher", spec:"One ephemeral worker per card." },
    { a:"dispatcher", b:"executor", spec:"One ephemeral worker per card." },
    { a:"dispatcher", b:"consolidator", spec:"One ephemeral worker per card." },
    { a:"dispatcher", b:"labbot", spec:"One ephemeral worker per card." },
    { a:"dispatcher", b:"seedr", spec:"One ephemeral worker per card." },
    { a:"coder", b:"bus", spec:"Workers publish results back to the bus, then exit." },
    { a:"researcher", b:"bus", spec:"Workers publish results back to the bus, then exit." },
    { a:"executor", b:"bus", spec:"Workers publish results back to the bus, then exit." },
    { a:"consolidator", b:"bus", spec:"Workers publish results back to the bus, then exit." },
    { a:"researcher", b:"router", spec:"Workers run inference via the router (27B / Claude)." },
    { a:"coder", b:"router", spec:"Workers run inference via the router (27B / Claude)." },
    { a:"router", b:"m9b", spec:"Task NLP → the 9B." },
    { a:"router", b:"m27b", spec:"Agent + long-context calls → the 27B." },
    { a:"router", b:"nomic", spec:"Embedding requests → nomic." },
    { a:"router", b:"claude", spec:"The hard ~5% → Claude." },
    { a:"gateway", b:"neo4j", spec:"The gateway queries the knowledge graph." },
    { a:"gateway", b:"postgres", spec:"The gateway queries the warehouse." },
    { a:"gateway", b:"bus", spec:"The gateway publishes / subscribes on the bus." },
    { a:"gateway", b:"keycloak", spec:"The gateway authenticates via Keycloak (OIDC)." },
    { a:"sentinel", b:"bus", spec:"Sentinel watches consumer lag + model health on the bus." },
  ],
};
